version: '3.8'

services:
  # NGINX Service (Proxy for Load Balancing)
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:8080"  # Map NGINX's port 8080 to local 8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount custom NGINX config
    depends_on:
      - ping-server
      - tracert-server  # NGINX depends on these services

  # Ping Server
  ping-server:
    build:
      context: ./ping_server  # Path to the ping_server directory
    container_name: ping-server
    ports:
      - "5000:5000"  # Expose port for ping requests
    environment:
      - FLASK_APP=ping_server.py  # Set the environment variable for Flask

  # Tracert Server
  tracert-server:
    build:
      context: ./tracert_server  # Path to the tracert_server directory
    container_name: tracert-server
    ports:
      - "5001:5000"  # Expose port for tracert requests
    environment:
      - FLASK_APP=tracert_server.py  # Set the environment variable for Flask
